window.onload = function () {
    console.log('--Math--')
    console.log(`Math.abs(-10) -> `, Math.abs(-10))
    console.log(`Math.acos(-1) -> `, Math.acos(-1))
    console.log(`Math.asin(-1) -> `, Math.asin(-1))
    console.log(`Math.atan(45) -> `, Math.atan(45))
    console.log(`Math.ceil(3.1) -> `, Math.ceil(3.1))
    console.log(`Math.floor(3.1) -> `, Math.floor(3.1))
    console.log(`Math.cos(60 * (2 * Math.PI) / 360) -> `, Math.cos(60 * (2 * Math.PI) / 360))
    console.log(`Math.sin(60 * (2 * Math.PI) / 360) -> `, Math.sin(30 * (2 * Math.PI) / 360))
    console.log(`Math.exp(2) -> `, Math.exp(2))
    console.log(`Math.E -> `, Math.E)
    console.log(`Math.LN10 -> `, Math.LN10)
    console.log(`Math.LN2 -> `, Math.LN2)
    console.log(`Math.LOG2E -> `, Math.LOG2E)
    console.log(`Math.LOG10E -> `, Math.LOG10E)
    console.log(`Math.log(10) -> `, Math.log(10))
    console.log(`Math.max(1, 2, 3) -> `,Math.max(1, 2, 3))
    console.log(`Math.pow(4, 0.5) -> `,Math.pow(4, 0.5))
    // Number
    console.log('--Number--')
    console.log(`Number.MAX_VALUE -> `,Number.MAX_VALUE)
    console.log(`Number.MAX_SAFE_INTEGER -> `,Number.MAX_SAFE_INTEGER)
    console.log(`Number.MIN_VALUE -> `,Number.MIN_VALUE)
    console.log(`Number.MIN_SAFE_INTEGER -> `,Number.MIN_SAFE_INTEGER)
    console.log(Number.EPSILON)
    console.log(Number.POSITIVE_INFINITY)
    console.log(Number.NEGATIVE_INFINITY)
    console.log(1.5.toFixed(2))
    console.log(1.5.toPrecision(1))
    console.log(parseFloat('1.5 Hello World'))
    console.log(parseInt('1.5 Hello World'))
}
